const filterData = [
    {
        nameAZ: 'Hamısı',
        nameEN: 'All',
        nameRU: 'Все',
        data: [
            {
                img: "../img/product/alma.png",
                titleAZ: 'Alma',
                titleEN: 'Apple',
                titleRU: 'Яблоко',
                cost: 5
            },
            {
                img: "../img/product/gavali.jpg",
                titleAZ: 'Gavalı',
                titleEN: 'Plum',
                titleRU: 'Слива',
                cost: 3
            },
            {
                img: "../img/product/armud.jpg",
                titleAZ: 'Armud',
                titleEN: 'Pear',
                titleRU: 'Груша',
                cost: 7
            },
            {
                img: "../img/product/gilas.jpg",
                titleAZ: 'Gilas',
                titleEN: 'Cherry',
                titleRU: 'Вишня',
                cost: 8
            },
            {
                img: "../img/product/qoz.jpg",
                titleAZ: 'Qoz',
                titleEN: 'Walnut',
                titleRU: 'Грецкий орех',
                cost: 2
            },
            {
                img: "../img/product/saftali.jpg",
                titleAZ: 'Şaftalı',
                titleEN: 'Peach',
                titleRU: 'Персик',
                cost: 4
            },
            {
                img: "../img/product/taxil.jpg",
                titleAZ: 'Taxıl',
                titleEN: 'Grain',
                titleRU: 'Зерно',
                cost: 11
            },
            {
                img: "../img/product/portagal.jpg",
                titleAZ: 'Portağal',
                titleEN: 'Orange',
                titleRU: 'Апельсин',
                cost: 4
            },
            {
                img: "../img/product/ting.jpg",
                titleAZ: 'Müxtəlif tinglər',
                titleEN: 'Different tings',
                titleRU: 'Разные оттенки',
                cost: 50
            },
            {
                img: "../img/product/pomidor.jpg",
                titleAZ: 'Pomidor',
                titleEN: 'Tomato',
                titleRU: 'Помидор',
                cost: 1
            },
            {
                img: "../img/product/cugundur.jpg",
                titleAZ: 'Çuğundur',
                titleEN: 'Beet',
                titleRU: 'Свекла',
                cost: 3
            },
            {
                img: "../img/product/kələm.jpg",
                titleAZ: 'Kələm',
                titleEN: 'Cabbage',
                titleRU: 'Капуста',
                cost: 6
            },
            {
                img: "../img/product/soğan.jpg",
                titleAZ: 'Soğan',
                titleEN: 'Onion',
                titleRU: 'Лук',
                cost: 1
            },
            {
                img: "../img/product/xiyar.jpg",
                titleAZ: 'Xiyar',
                titleEN: 'Cucumber',
                titleRU: 'Огурец',
                cost: 5
            },
            {
                img: "../img/product/yerkoku.jpg",
                titleAZ: 'Yerkökü',
                titleEN: 'Carrot',
                titleRU: 'Морковь',
                cost: 2
            }
        ]
    },
    {
        nameAZ: 'Meyvələr',
        nameEN: 'Fruits',
        nameRU: 'Фрукты',
        data: [
            {
                img: "../img/product/alma.png",
                titleAZ: 'Alma',
                titleEN: 'Apple',
                titleRU: 'Яблоко',
                cost: 5
            },
            {
                img: "../img/product/gavali.jpg",
                titleAZ: 'Gavalı',
                titleEN: 'Plum',
                titleRU: 'Слива',
                cost: 3
            },
            {
                img: "../img/product/armud.jpg",
                titleAZ: 'Armud',
                titleEN: 'Pear',
                titleRU: 'Груша',
                cost: 7
            },
            {
                img: "../img/product/gilas.jpg",
                titleAZ: 'Gilas',
                titleEN: 'Cherry',
                titleRU: 'Вишня',
                cost: 8
            },
            {
                img: "../img/product/qoz.jpg",
                titleAZ: 'Qoz',
                titleEN: 'Walnut',
                titleRU: 'Грецкий орех',
                cost: 2
            },
            {
                img: "../img/product/saftali.jpg",
                titleAZ: 'Şaftalı',
                titleEN: 'Peach',
                titleRU: 'Персик',
                cost: 4
            },
            {
                img: "../img/product/portagal.jpg",
                titleAZ: 'Portağal',
                titleEN: 'Orange',
                titleRU: 'Апельсин',
                cost: 4
            }
        ]
    },
    {
        nameAZ: 'Tərəvəzlər',
        nameEN: 'Vegetables',
        nameRU: 'Овощи',
        data: [
            {
                img: "../img/product/pomidor.jpg",
                titleAZ: 'Pomidor',
                titleEN: 'Tomato',
                titleRU: 'Помидор',
                cost: 1
            },
            {
                img: "../img/product/cugundur.jpg",
                titleAZ: 'Çuğundur',
                titleEN: 'Beet',
                titleRU: 'Свекла',
                cost: 3
            },
            {
                img: "../img/product/kələm.jpg",
                titleAZ: 'Kələm',
                titleEN: 'Cabbage',
                titleRU: 'Капуста',
                cost: 6
            },
            {
                img: "../img/product/soğan.jpg",
                titleAZ: 'Soğan',
                titleEN: 'Onion',
                titleRU: 'Лук',
                cost: 1
            },
            {
                img: "../img/product/xiyar.jpg",
                titleAZ: 'Xiyar',
                titleEN: 'Cucumber',
                titleRU: 'Огурец',
                cost: 5
            },
            {
                img: "../img/product/yerkoku.jpg",
                titleAZ: 'Yerkökü',
                titleEN: 'Carrot',
                titleRU: 'Морковь',
                cost: 2
            }
        ]
    },
    {
        nameAZ: 'Taxıllar',
        nameEN: 'Grains',
        nameRU: 'Зерновые',
        data: [
            {
                img: "../img/product/taxil.jpg",
                titleAZ: 'Taxıl',
                titleEN: 'Grain',
                titleRU: 'Зерно',
                cost: 11
            }
        ]
    },
    {
        nameAZ: 'Digər',
        nameEN: 'Others',
        nameRU: 'Другие',
        data: [
            {
                img: "../img/product/ting.jpg",
                titleAZ: 'Müxtəlif tinglər',
                titleEN: 'Different tings',
                titleRU: 'Разные оттенки',
                cost: 50
            }
        ]
    }
]

const productData = [
    {
        img: "../img/product/alma.png",
        titleAZ: 'Alma',
        titleEN: 'Apple',
        titleRU: 'Яблоко',
        cost: 5,
        sliderImg1: '../img/product/product-img1.png',
        sliderImg2: '../img/product/product-img2.png',
        sliderImg3: '../img/product/product-img3.png'
    },
    {
        img: "../img/product/gavali.jpg",
        titleAZ: 'Gavalı',
        titleEN: 'Plum',
        titleRU: 'Слива',
        cost: 3,
        sliderImg1: '../img/product/product-img4.jpeg',
        sliderImg2: '../img/product/product-img5.jpg',
        sliderImg3: '../img/product/product-img6.jpg'
    },
    {
        img: "../img/product/armud.jpg",
        titleAZ: 'Armud',
        titleEN: 'Pear',
        titleRU: 'Груша',
        cost: 7,
        sliderImg1: '../img/product/product-img7.jpg',
        sliderImg2: '../img/product/product-img8.jpg',
        sliderImg3: '../img/product/product-img9.jpg'
    },
    {
        img: "../img/product/gilas.jpg",
        titleAZ: 'Gilas',
        titleEN: 'Cherry',
        titleRU: 'Вишня',
        cost: 8,
        sliderImg1: '../img/product/product-img10.jpg',
        sliderImg2: '../img/product/product-img11.jpg',
        sliderImg3: '../img/product/product-img12.jpg'
    },
    {
        img: "../img/product/qoz.jpg",
        titleAZ: 'Qoz',
        titleEN: 'Walnut',
        titleRU: 'Грецкий орех',
        cost: 2,
        sliderImg1: '../img/product/product-img13.jpg',
        sliderImg2: '../img/product/product-img14.jpg',
        sliderImg3: '../img/product/product-img15.jpg'
    },
    {
        img: "../img/product/saftali.jpg",
        titleAZ: 'Şaftalı',
        titleEN: 'Peach',
        titleRU: 'Персик',
        cost: 4,
        sliderImg1: '../img/product/product-img16.jpg',
        sliderImg2: '../img/product/product-img17.jpg',
        sliderImg3: '../img/product/product-img18.jpg'
    },
    {
        img: "../img/product/taxil.jpg",
        titleAZ: 'Taxıl',
        titleEN: 'Grain',
        titleRU: 'Зерно',
        cost: 11,
        sliderImg1: '../img/product/product-img19.jpg',
        sliderImg2: '../img/product/product-img20.jpg',
        sliderImg3: '../img/product/product-img21.jpg'
    },
    {
        img: "../img/product/portagal.jpg",
        titleAZ: 'Portağal',
        titleEN: 'Orange',
        titleRU: 'Апельсин',
        cost: 4,
        sliderImg1: '../img/product/product-img22.jpg',
        sliderImg2: '../img/product/product-img23.jpeg',
        sliderImg3: '../img/product/product-img24.jpg'
    },
    {
        img: "../img/product/ting.jpg",
        titleAZ: 'Müxtəlif tinglər',
        titleEN: 'Different tings',
        titleRU: 'Разные оттенки',
        cost: 50,
        sliderImg1: '../img/product/product-img25.jpg',
        sliderImg2: '../img/product/product-img26.jpg',
        sliderImg3: '../img/product/product-img27.jpg'
    },
    {
        img: "../img/product/pomidor.jpg",
        titleAZ: 'Pomidor',
        titleEN: 'Tomato',
        titleRU: 'Помидор',
        cost: 1,
        sliderImg1: '../img/product/product-img28.jpg',
        sliderImg2: '../img/product/product-img29.jpg',
        sliderImg3: '../img/product/product-img30.jpg'
    },
    {
        img: "../img/product/cugundur.jpg",
        titleAZ: 'Çuğundur',
        titleEN: 'Beet',
        titleRU: 'Свекла',
        cost: 3,
        sliderImg1: '../img/product/product-img31.jpg',
        sliderImg2: '../img/product/product-img32.jpeg',
        sliderImg3: '../img/product/product-img33.jpg'
    },
    {
        img: "../img/product/kələm.jpg",
        titleAZ: 'Kələm',
        titleEN: 'Cabbage',
        titleRU: 'Капуста',
        cost: 6,
        sliderImg1: '../img/product/product-img34.jpg',
        sliderImg2: '../img/product/product-img35.jpg',
        sliderImg3: '../img/product/product-img36.jpg'
    },
    {
        img: "../img/product/soğan.jpg",
        titleAZ: 'Soğan',
        titleEN: 'Onion',
        titleRU: 'Лук',
        cost: 1,
        sliderImg1: '../img/product/product-img37.jpg',
        sliderImg2: '../img/product/product-img38.jpg',
        sliderImg3: '../img/product/product-img39.jpg'
    },
    {
        img: "../img/product/xiyar.jpg",
        titleAZ: 'Xiyar',
        titleEN: 'Cucumber',
        titleRU: 'Огурец',
        cost: 5,
        sliderImg1: '../img/product/product-img40.jpg',
        sliderImg2: '../img/product/product-img41.jpg',
        sliderImg3: '../img/product/product-img42.jpg'
    },
    {
        img: "../img/product/yerkoku.jpg",
        titleAZ: 'Yerkökü',
        titleEN: 'Carrot',
        titleRU: 'Морковь',
        cost: 2,
        sliderImg1: '../img/product/product-img43.jpg',
        sliderImg2: '../img/product/product-img44.jpg',
        sliderImg3: '../img/product/product-img45.jpg'
    }
]

// Convert to Azerbaijani
const changeLangToAz = [
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    "Meyvələr",
    'Daha çox...',
    'Tərəvəzlər',
    'Daha çox...',
    'Taxıl',
    'Daha çox...',
    "Meyvələr",
    'Daha çox...',
    'Tərəvəzlər',
    'Daha çox...',
    'Taxıl',
    'Daha çox...',
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Biz kimik?',
    'Əslində hər şey illər əvvəl İsmayıllı rayonunda ailəvi səfərdə olarkən baş verdi. İsmayıllı rayonunun füsunkar təbiətinin gözəlliyi bizdə nə vaxtsa burada kənd təsərrüfatı ilə məşğul olmaq istəyimizi oyatdı. Sonradan bu məsələni bizimlə müzakirə etdikdən sonra dostlar biz İsmayıllıda təsərrüfat qurmaq qərarına gəldik.Bizdə sürətdən geri qalmadıq. Qısa müddət ərzində əldə etdiyimiz uğur və daha da sürətlə inkişaf etməyimiz işimizə olan sevgimizin göstəricisidir. t bununla dayanaraq məhsul çeşidimizi əkin və toxumçuluqla genişləndirdik.Qısa müddət ərzində BAĞIN layihələndirilməsi və əkilməsi, ən son texnoloji yeniliklərlə damcı suvarma sistemlərinin qurulması kimi çətin işləri uğurla başa çatdırdıq. 2022-ci ildə əsas hədəfimiz al, brendimizi ölkə xaricindəki rəflərdə “made in AZERBAIJAN” adına layiq görməkdir. Növbəti hədəfləri sizinlə bölüşmək istəyirik',
    'Hörmətlə <br> MELADORA komandası',
    'Orqanik',
    'Məmnunluq',
    'Yüksək keyfiyyət',
    "Bağlar",
    'Taxıl',
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    "Üzüm",
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    "Kələm",
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    "Xidmətlər",
    'Damla suvarma sistemləri',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Proyektləşdirmə',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Açıq təhvil bağçaların tikintisi',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Sosial Məsuliyyət',
    'Biz bir sahibkar olaraq təkcə qazanc əldə etmək deyil, həm də müxtəlif sahələrdə cəmiyyətə faydalı olmağın vacibliyini dərk edir və bu istiqamətdə fəaliyyətimizi davam etdiririk. Biz əhalinin müəyyən təbəqələrinin həyatını yaxşılaşdırmaq üçün sosial əhəmiyyətli proqramlar həyata keçiririk.<br><br>Dostlarımız və ətrafımız bizi yaxşı tanıyır.<br><br>Və biz sosial yönümlü şirkət olmaqdan qürur duyuruq.',
    "Bloqlar",
    "Məhsulların saxlanması",
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    "Əkinçilik",
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Əkinlərin suvarılması',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Əlaqə',
    "Ərizə forması",
    'İsmayıllı rayonu, Qalıncaq kəndi',
    'Bakı, Meladora MMC',
    "Menyular",
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Faydalı bağlantılar',
    'Tez-tez soruşulan suallar',
    "Karyera",
    "Xidmət şəbəkəsi",
    'FAQ',
    'Təhlükəsizlik',
    'Şərtlər və Qaydalar',
    'Müəlliflik hüququ 2022 - ',
    'Tərəfindən dəstəklənməkdədir '
]
const changeLangToAz2 = [
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    "Meyvələr",
    'Daha çox...',
    'Tərəvəzlər',
    'Daha çox...',
    'Taxıl',
    'Daha çox...',
    "Meyvələr",
    'Daha çox...',
    'Tərəvəzlər',
    'Daha çox...',
    'Taxıl',
    'Daha çox...',
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Biz kimik?',
    'Əslində hər şey illər əvvəl İsmayıllı rayonunda ailəvi səfərdə olarkən baş verdi. İsmayıllı rayonunun füsunkar təbiətinin gözəlliyi bizdə nə vaxtsa burada kənd təsərrüfatı ilə məşğul olmaq istəyimizi oyatdı. Sonradan bu məsələni bizimlə müzakirə etdikdən sonra dostlar biz İsmayıllıda təsərrüfat qurmaq qərarına gəldik.Bizdə sürətdən geri qalmadıq. Qısa müddət ərzində əldə etdiyimiz uğur və daha da sürətlə inkişaf etməyimiz işimizə olan sevgimizin göstəricisidir.Alma, armud, nektarin, gavalı, gilas və qoz yetişdirməklə kifayətlənmədik, əkin və toxumçuluqla məhsul çeşidimizi genişləndirdik.Qısa müddət ərzində BAĞIN layihələndirilməsi və əkilməsi, ən son texnoloji yeniliklərlə damcı suvarma sistemlərinin qurulması kimi çətin işləri uğurla başa çatdırdıq. 2022-ci ildə əsas hədəfimiz al, brendimizi ölkə xaricindəki rəflərdə “made in AZERBAIJAN” adına layiq görməkdir. Növbəti hədəfləri sizinlə bölüşmək istəyirik',
    'Hörmətlə <br> MELADORA komandası',
    'Orqanik',
    'Məmnunluq',
    'Yüksək keyfiyyət',
    "Bağlar",
    'Taxıl',
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    "Üzüm",
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    "Kələm",
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    'Məhsullar',
    'Hamısı',
    "Meyvələr",
    'Tərəvəzlər',
    'Taxıllar',
    'Digərləri',
    'Alma',
    'Gavalı',
    "Armud",
    'Albalı',
    'Qoz',
    'Şaftalı',
    'Portağal',
    "Xidmətlər",
    'Damla suvarma sistemləri',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Proyektləşdirmə',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Açıq təhvil bağçaların tikintisi',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Sosial Məsuliyyət',
    'Biz bir sahibkar olaraq təkcə qazanc əldə etmək deyil, həm də müxtəlif sahələrdə cəmiyyətə faydalı olmağın vacibliyini dərk edir və bu istiqamətdə fəaliyyətimizi davam etdiririk. Biz əhalinin müəyyən təbəqələrinin həyatını yaxşılaşdırmaq üçün sosial əhəmiyyətli proqramlar həyata keçiririk.<br><br>Dostlarımız və ətrafımız bizi yaxşı tanıyır.<br><br>Və biz sosial yönümlü şirkət olmaqdan qürur duyuruq.',
    "Bloqlar",
    "Məhsulların saxlanması",
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    "Əkinçilik",
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Əkinlərin suvarılması',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Əlaqə',
    "Ərizə forması",
    'İsmayıllı rayonu, Qalıncaq kəndi',
    'Bakı, Meladora MMC',
    "Menyular",
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Faydalı bağlantılar',
    'Tez-tez soruşulan suallar',
    "Karyera",
    "Xidmət şəbəkəsi",
    'FAQ',
    'Təhlükəsizlik',
    'Şərtlər və Qaydalar',
    'Müəlliflik hüququ 2022 - ',
    'Tərəfindən dəstəklənməkdədir '
]
const changeLangToAz3 = [
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    "Meyvələr",
    'Daha çox...',
    'Tərəvəzlər',
    'Daha çox...',
    'Taxıl',
    'Daha çox...',
    "Meyvələr",
    'Daha çox...',
    'Tərəvəzlər',
    'Daha çox...',
    'Taxıl',
    'Daha çox...',
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Biz kimik?',
    'Əslində hər şey illər əvvəl İsmayıllı rayonunda ailəvi səfərdə olarkən baş verdi. İsmayıllı rayonunun füsunkar təbiətinin gözəlliyi bizdə nə vaxtsa burada kənd təsərrüfatı ilə məşğul olmaq istəyimizi oyatdı. Sonradan bu məsələni bizimlə müzakirə etdikdən sonra dostlar biz İsmayıllıda təsərrüfat qurmaq qərarına gəldik.Bizdə sürətdən geri qalmadıq. Qısa müddət ərzində əldə etdiyimiz uğur və daha da sürətlə inkişaf etməyimiz işimizə olan sevgimizin göstəricisidir.Alma, armud, nektarin, gavalı, gilas və qoz yetişdirməklə kifayətlənmədik, əkin və toxumçuluqla məhsul çeşidimizi genişləndirdik.Qısa müddət ərzində BAĞIN layihələndirilməsi və əkilməsi, ən son texnoloji yeniliklərlə damcı suvarma sistemlərinin qurulması kimi çətin işləri uğurla başa çatdırdıq. 2022-ci ildə əsas hədəfimiz al, brendimizi ölkə xaricindəki rəflərdə “made in AZERBAIJAN” adına layiq görməkdir. Növbəti hədəfləri sizinlə bölüşmək istəyirik',
    'Hörmətlə <br> MELADORA komandası',
    'Orqanik',
    'Məmnunluq',
    'Yüksək keyfiyyət',
    "Bağlar",
    'Taxıl',
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    "Üzüm",
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    "Kələm",
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    'Məhsullar',
    'Hamısı',
    "Meyvələr",
    'Tərəvəzlər',
    'Taxıllar',
    'Digərləri',
    "Pomidor",
    'Çuğundur',
    "Kələm",
    'Soğan',
    'Xiyar',
    'Yerkökü',
    "Xidmətlər",
    'Damla suvarma sistemləri',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Proyektləşdirmə',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Açıq təhvil bağçaların tikintisi',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Sosial Məsuliyyət',
    'Biz bir sahibkar olaraq təkcə qazanc əldə etmək deyil, həm də müxtəlif sahələrdə cəmiyyətə faydalı olmağın vacibliyini dərk edir və bu istiqamətdə fəaliyyətimizi davam etdiririk. Biz əhalinin müəyyən təbəqələrinin həyatını yaxşılaşdırmaq üçün sosial əhəmiyyətli proqramlar həyata keçiririk.<br><br>Dostlarımız və ətrafımız bizi yaxşı tanıyır.<br><br>Və biz sosial yönümlü şirkət olmaqdan qürur duyuruq.',
    "Bloqlar",
    "Məhsulların saxlanması",
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    "Əkinçilik",
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Əkinlərin suvarılması',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Əlaqə',
    "Ərizə forması",
    'İsmayıllı rayonu, Qalıncaq kəndi',
    'Bakı, Meladora MMC',
    "Menyular",
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Faydalı bağlantılar',
    'Tez-tez soruşulan suallar',
    "Karyera",
    "Xidmət şəbəkəsi",
    'FAQ',
    'Təhlükəsizlik',
    'Şərtlər və Qaydalar',
    'Müəlliflik hüququ 2022 - ',
    'Tərəfindən dəstəklənməkdədir '
]
const changeLangToAz4 = [
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    "Meyvələr",
    'Daha çox...',
    'Tərəvəzlər',
    'Daha çox...',
    'Taxıl',
    'Daha çox...',
    "Meyvələr",
    'Daha çox...',
    'Tərəvəzlər',
    'Daha çox...',
    'Taxıl',
    'Daha çox...',
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Biz kimik?',
    'Əslində hər şey illər əvvəl İsmayıllı rayonunda ailəvi səfərdə olarkən baş verdi. İsmayıllı rayonunun füsunkar təbiətinin gözəlliyi bizdə nə vaxtsa burada kənd təsərrüfatı ilə məşğul olmaq istəyimizi oyatdı. Sonradan bu məsələni bizimlə müzakirə etdikdən sonra dostlar biz İsmayıllıda təsərrüfat qurmaq qərarına gəldik.Bizdə sürətdən geri qalmadıq. Qısa müddət ərzində əldə etdiyimiz uğur və daha da sürətlə inkişaf etməyimiz işimizə olan sevgimizin göstəricisidir.Alma, armud, nektarin, gavalı, gilas və qoz yetişdirməklə kifayətlənmədik, əkin və toxumçuluqla məhsul çeşidimizi genişləndirdik.Qısa müddət ərzində BAĞIN layihələndirilməsi və əkilməsi, ən son texnoloji yeniliklərlə damcı suvarma sistemlərinin qurulması kimi çətin işləri uğurla başa çatdırdıq. 2022-ci ildə əsas hədəfimiz al, brendimizi ölkə xaricindəki rəflərdə “made in AZERBAIJAN” adına layiq görməkdir. Növbəti hədəfləri sizinlə bölüşmək istəyirik',
    'Hörmətlə <br> MELADORA komandası',
    'Orqanik',
    'Məmnunluq',
    'Yüksək keyfiyyət',
    "Bağlar",
    'Taxıl',
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    "Üzüm",
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    "Kələm",
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    'Məhsullar',
    'Hamısı',
    "Meyvələr",
    'Tərəvəzlər',
    'Taxıllar',
    'Digərləri',
    'Taxıl',
    "Xidmətlər",
    'Damla suvarma sistemləri',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Proyektləşdirmə',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Açıq təhvil bağçaların tikintisi',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Sosial Məsuliyyət',
    'Biz bir sahibkar olaraq təkcə qazanc əldə etmək deyil, həm də müxtəlif sahələrdə cəmiyyətə faydalı olmağın vacibliyini dərk edir və bu istiqamətdə fəaliyyətimizi davam etdiririk. Biz əhalinin müəyyən təbəqələrinin həyatını yaxşılaşdırmaq üçün sosial əhəmiyyətli proqramlar həyata keçiririk.<br><br>Dostlarımız və ətrafımız bizi yaxşı tanıyır.<br><br>Və biz sosial yönümlü şirkət olmaqdan qürur duyuruq.',
    "Bloqlar",
    "Məhsulların saxlanması",
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    "Əkinçilik",
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Əkinlərin suvarılması',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Əlaqə',
    "Ərizə forması",
    'İsmayıllı rayonu, Qalıncaq kəndi',
    'Bakı, Meladora MMC',
    "Menyular",
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Faydalı bağlantılar',
    'Tez-tez soruşulan suallar',
    "Karyera",
    "Xidmət şəbəkəsi",
    'FAQ',
    'Təhlükəsizlik',
    'Şərtlər və Qaydalar',
    'Müəlliflik hüququ 2022 - ',
    'Tərəfindən dəstəklənməkdədir '
]
const changeLangToAz5 = [
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    "Meyvələr",
    'Daha çox...',
    'Tərəvəzlər',
    'Daha çox...',
    'Taxıl',
    'Daha çox...',
    "Meyvələr",
    'Daha çox...',
    'Tərəvəzlər',
    'Daha çox...',
    'Taxıl',
    'Daha çox...',
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Biz kimik?',
    'Əslində hər şey illər əvvəl İsmayıllı rayonunda ailəvi səfərdə olarkən baş verdi. İsmayıllı rayonunun füsunkar təbiətinin gözəlliyi bizdə nə vaxtsa burada kənd təsərrüfatı ilə məşğul olmaq istəyimizi oyatdı. Sonradan bu məsələni bizimlə müzakirə etdikdən sonra dostlar biz İsmayıllıda təsərrüfat qurmaq qərarına gəldik.Bizdə sürətdən geri qalmadıq. Qısa müddət ərzində əldə etdiyimiz uğur və daha da sürətlə inkişaf etməyimiz işimizə olan sevgimizin göstəricisidir.Alma, armud, nektarin, gavalı, gilas və qoz yetişdirməklə kifayətlənmədik, əkin və toxumçuluqla məhsul çeşidimizi genişləndirdik.Qısa müddət ərzində BAĞIN layihələndirilməsi və əkilməsi, ən son texnoloji yeniliklərlə damcı suvarma sistemlərinin qurulması kimi çətin işləri uğurla başa çatdırdıq. 2022-ci ildə əsas hədəfimiz al, brendimizi ölkə xaricindəki rəflərdə “made in AZERBAIJAN” adına layiq görməkdir. Növbəti hədəfləri sizinlə bölüşmək istəyirik',
    'Hörmətlə <br> MELADORA komandası',
    'Orqanik',
    'Məmnunluq',
    'Yüksək keyfiyyət',
    "Bağlar",
    'Taxıl',
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    "Üzüm",
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    "Kələm",
    "Salam, həqiqətən də arxasınca getmək dərddir. Azad insanımızın ləzzətlərini görək, bədənin rahatlığından və onun çox vaxt kor etdiyi bu kimi şeylərdən azad olaq. Dözüm!",
    'Məhsullar',
    'Hamısı',
    "Meyvələr",
    'Tərəvəzlər',
    'Taxıllar',
    'Digərləri',
    'Fərqli tinqlər',
    "Xidmətlər",
    'Damla suvarma sistemləri',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Proyektləşdirmə',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Açıq təhvil bağçaların tikintisi',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Sosial Məsuliyyət',
    'Biz bir sahibkar olaraq təkcə qazanc əldə etmək deyil, həm də müxtəlif sahələrdə cəmiyyətə faydalı olmağın vacibliyini dərk edir və bu istiqamətdə fəaliyyətimizi davam etdiririk. Biz əhalinin müəyyən təbəqələrinin həyatını yaxşılaşdırmaq üçün sosial əhəmiyyətli proqramlar həyata keçiririk.<br><br>Dostlarımız və ətrafımız bizi yaxşı tanıyır.<br><br>Və biz sosial yönümlü şirkət olmaqdan qürur duyuruq.',
    "Bloqlar",
    "Məhsulların saxlanması",
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    "Əkinçilik",
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Əkinlərin suvarılması',
    'Şirkətin özü çox uğurlu şirkətdir. Biz isə onları ittiham edirik, görürlər ki, ittiham edənlərin yumşaqlığı yaltaqlığa düşür! Amma o, ixtiraçının ləzzətini əmək ağrısından qurtarmaq istəyir!',
    'Əlaqə',
    "Ərizə forması",
    'İsmayıllı rayonu, Qalıncaq kəndi',
    'Bakı, Meladora MMC',
    "Menyular",
    'Biz kimik?',
    "Bağlar",
    'Məhsullar',
    "Xidmətlər",
    'Sosial Məsuliyyət',
    'Əlaqə',
    'Faydalı bağlantılar',
    'Tez-tez soruşulan suallar',
    "Karyera",
    "Xidmət şəbəkəsi",
    'FAQ',
    'Təhlükəsizlik',
    'Şərtlər və Qaydalar',
    'Müəlliflik hüququ 2022 - ',
    'Tərəfindən dəstəklənməkdədir '
]

const changeLangToAzForValue = [
    'Axtar',
    'Göndər'
]

const changeLangToAzForPlaceholder = [
    'Axtarış',
    'Adınız, Soyadınız*',
    'Telefon*',
    'E-poçt*',
    'Mesajınız'
]

// Convert to English
const changeLangToEn = [
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Fruits',
    'More...',
    'Vegetables',
    'More...',
    'Grain',
    'More...',
    'Fruits',
    'More...',
    'Vegetables',
    'More...',
    'Grain',
    'More...',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Who are we?',
    "In fact, it all happened years ago when we were on a family trip in Ismayilli district. The beauty of the charming nature of Ismayilli region awakened our desire to one day be engaged in rural farming here. Later, after discussing this issue with our friends, we decided to establish a farm in Ismailli.We did not lag behind the speed of time in our growth. The success we achieved in a short period of time and the fact that we continue to grow faster is an indication of our love for our work. By growing apples, pears, nectarines, plums, cherries and walnuts we didn't stop there, we expanded our product range with planting and seed production. In a short time, we successfully completed difficult tasks such as designing and planting GARDEN, building drip irrigation systems with the latest technological innovations. In 2022, our main goal is to make our brand appear on shelves outside the country worthy of the name 'made in AZERBAIJAN'. We wish to share the next goals with you.",
    'Sincerely <br> MELADORA team',
    'Organic',
    'Satisfaction',
    'High quality',
    'Gardens',
    'Grain',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Grape',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Cabbage',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Products',
    'All',
    'Fruits',
    'Vegetables',
    'Grains',
    'Others',
    'Apple',
    'Plum',
    'Pear',
    'Cherry',
    'Walnut',
    'Peach',
    'Grain',
    'Orange',
    'Different tings',
    'Tomato',
    'Beet',
    'Cabbage',
    'Onion',
    'Cucumber',
    'Carrot',
    'Services',
    'Drip irrigation systems',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Projecting',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Construction of turnkey gardens',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Social responsibility',
    'As an entrepreneur, we understand the need not only to make a profit, but also to be useful to the society in various fields, and we continue our activities in this direction. We implement socially important programs to improve the lives of certain sections of the population.<br><br>Our friends and circle know us well.<br><br>And we are proud to be a socially oriented company.',
    'Blogs',
    'Storage of products',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Cultivation of crops',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Watering of crops',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Contact',
    'Application Form',
    'Ismayilli district, Kalinjak village',
    'Bakı, Meladora LLC',
    'Menus',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Useful links',
    'Frequently asked questions',
    'Career',
    'Service network',
    'FAQ',
    'Security',
    'Terms and conditions',
    'Copyright 2022 - ',
    'Powered by '
]
const changeLangToEn2 = [
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Fruits',
    'More...',
    'Vegetables',
    'More...',
    'Grain',
    'More...',
    'Fruits',
    'More...',
    'Vegetables',
    'More...',
    'Grain',
    'More...',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Who are we?',
    "In fact, it all happened years ago when we were on a family trip in Ismayilli district. The beauty of the charming nature of Ismayilli region awakened our desire to one day be engaged in rural farming here. Later, after discussing this issue with our friends, we decided to establish a farm in Ismailli.We did not lag behind the speed of time in our growth. The success we achieved in a short period of time and the fact that we continue to grow faster is an indication of our love for our work. By growing apples, pears, nectarines, plums, cherries and walnuts we didn't stop there, we expanded our product range with planting and seed production. In a short time, we successfully completed difficult tasks such as designing and planting GARDEN, building drip irrigation systems with the latest technological innovations. In 2022, our main goal is to make our brand appear on shelves outside the country worthy of the name 'made in AZERBAIJAN'. We wish to share the next goals with you.",
    'Sincerely <br> MELADORA team',
    'Organic',
    'Satisfaction',
    'High quality',
    'Gardens',
    'Grain',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Grape',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Cabbage',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Products',
    'All',
    'Fruits',
    'Vegetables',
    'Grains',
    'Others',
    'Apple',
    'Plum',
    'Pear',
    'Cherry',
    'Walnut',
    'Peach',
    'Orange',
    'Services',
    'Drip irrigation systems',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Projecting',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Construction of turnkey gardens',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Social responsibility',
    'As an entrepreneur, we understand the need not only to make a profit, but also to be useful to the society in various fields, and we continue our activities in this direction. We implement socially important programs to improve the lives of certain sections of the population.<br><br>Our friends and circle know us well.<br><br>And we are proud to be a socially oriented company.',
    'Blogs',
    'Storage of products',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Cultivation of crops',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Watering of crops',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Contact',
    'Application Form',
    'Ismayilli district, Kalinjak village',
    'Bakı, Meladora LLC',
    'Menus',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Useful links',
    'Frequently asked questions',
    'Career',
    'Service network',
    'FAQ',
    'Security',
    'Terms and conditions',
    'Copyright 2022 - ',
    'Powered by '
]
const changeLangToEn3 = [
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Fruits',
    'More...',
    'Vegetables',
    'More...',
    'Grain',
    'More...',
    'Fruits',
    'More...',
    'Vegetables',
    'More...',
    'Grain',
    'More...',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Who are we?',
    "In fact, it all happened years ago when we were on a family trip in Ismayilli district. The beauty of the charming nature of Ismayilli region awakened our desire to one day be engaged in rural farming here. Later, after discussing this issue with our friends, we decided to establish a farm in Ismailli.We did not lag behind the speed of time in our growth. The success we achieved in a short period of time and the fact that we continue to grow faster is an indication of our love for our work. By growing apples, pears, nectarines, plums, cherries and walnuts we didn't stop there, we expanded our product range with planting and seed production. In a short time, we successfully completed difficult tasks such as designing and planting GARDEN, building drip irrigation systems with the latest technological innovations. In 2022, our main goal is to make our brand appear on shelves outside the country worthy of the name 'made in AZERBAIJAN'. We wish to share the next goals with you.",
    'Sincerely <br> MELADORA team',
    'Organic',
    'Satisfaction',
    'High quality',
    'Gardens',
    'Grain',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Grape',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Cabbage',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Products',
    'All',
    'Fruits',
    'Vegetables',
    'Grains',
    'Others',
    'Tomato',
    'Beet',
    'Cabbage',
    'Onion',
    'Cucumber',
    'Carrot',
    'Services',
    'Drip irrigation systems',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Projecting',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Construction of turnkey gardens',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Social responsibility',
    'As an entrepreneur, we understand the need not only to make a profit, but also to be useful to the society in various fields, and we continue our activities in this direction. We implement socially important programs to improve the lives of certain sections of the population.<br><br>Our friends and circle know us well.<br><br>And we are proud to be a socially oriented company.',
    'Blogs',
    'Storage of products',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Cultivation of crops',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Watering of crops',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Contact',
    'Application Form',
    'Ismayilli district, Kalinjak village',
    'Bakı, Meladora LLC',
    'Menus',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Useful links',
    'Frequently asked questions',
    'Career',
    'Service network',
    'FAQ',
    'Security',
    'Terms and conditions',
    'Copyright 2022 - ',
    'Powered by '
]
const changeLangToEn4 = [
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Fruits',
    'More...',
    'Vegetables',
    'More...',
    'Grain',
    'More...',
    'Fruits',
    'More...',
    'Vegetables',
    'More...',
    'Grain',
    'More...',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Who are we?',
    "In fact, it all happened years ago when we were on a family trip in Ismayilli district. The beauty of the charming nature of Ismayilli region awakened our desire to one day be engaged in rural farming here. Later, after discussing this issue with our friends, we decided to establish a farm in Ismailli.We did not lag behind the speed of time in our growth. The success we achieved in a short period of time and the fact that we continue to grow faster is an indication of our love for our work. By growing apples, pears, nectarines, plums, cherries and walnuts we didn't stop there, we expanded our product range with planting and seed production. In a short time, we successfully completed difficult tasks such as designing and planting GARDEN, building drip irrigation systems with the latest technological innovations. In 2022, our main goal is to make our brand appear on shelves outside the country worthy of the name 'made in AZERBAIJAN'. We wish to share the next goals with you.",
    'Sincerely <br> MELADORA team',
    'Organic',
    'Satisfaction',
    'High quality',
    'Gardens',
    'Grain',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Grape',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Cabbage',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Products',
    'All',
    'Fruits',
    'Vegetables',
    'Grains',
    'Others',
    'Grain',
    'Services',
    'Drip irrigation systems',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Projecting',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Construction of turnkey gardens',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Social responsibility',
    'As an entrepreneur, we understand the need not only to make a profit, but also to be useful to the society in various fields, and we continue our activities in this direction. We implement socially important programs to improve the lives of certain sections of the population.<br><br>Our friends and circle know us well.<br><br>And we are proud to be a socially oriented company.',
    'Blogs',
    'Storage of products',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Cultivation of crops',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Watering of crops',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Contact',
    'Application Form',
    'Ismayilli district, Kalinjak village',
    'Bakı, Meladora LLC',
    'Menus',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Useful links',
    'Frequently asked questions',
    'Career',
    'Service network',
    'FAQ',
    'Security',
    'Terms and conditions',
    'Copyright 2022 - ',
    'Powered by '
]
const changeLangToEn5 = [
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Fruits',
    'More...',
    'Vegetables',
    'More...',
    'Grain',
    'More...',
    'Fruits',
    'More...',
    'Vegetables',
    'More...',
    'Grain',
    'More...',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Who are we?',
    "In fact, it all happened years ago when we were on a family trip in Ismayilli district. The beauty of the charming nature of Ismayilli region awakened our desire to one day be engaged in rural farming here. Later, after discussing this issue with our friends, we decided to establish a farm in Ismailli.We did not lag behind the speed of time in our growth. The success we achieved in a short period of time and the fact that we continue to grow faster is an indication of our love for our work. By growing apples, pears, nectarines, plums, cherries and walnuts we didn't stop there, we expanded our product range with planting and seed production. In a short time, we successfully completed difficult tasks such as designing and planting GARDEN, building drip irrigation systems with the latest technological innovations. In 2022, our main goal is to make our brand appear on shelves outside the country worthy of the name 'made in AZERBAIJAN'. We wish to share the next goals with you.",
    'Sincerely <br> MELADORA team',
    'Organic',
    'Satisfaction',
    'High quality',
    'Gardens',
    'Grain',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Grape',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Cabbage',
    "Hello, it's really a pain to be followed. Let us see the pleasures of our free man, and be freed from the ease of the body, and the like, which are often blinded by him. Enduring!",
    'Products',
    'All',
    'Fruits',
    'Vegetables',
    'Grains',
    'Others',
    'Different tings',
    'Services',
    'Drip irrigation systems',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Projecting',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Construction of turnkey gardens',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Social responsibility',
    'As an entrepreneur, we understand the need not only to make a profit, but also to be useful to the society in various fields, and we continue our activities in this direction. We implement socially important programs to improve the lives of certain sections of the population.<br><br>Our friends and circle know us well.<br><br>And we are proud to be a socially oriented company.',
    'Blogs',
    'Storage of products',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Cultivation of crops',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Watering of crops',
    'The company itself is a very successful company. And we accuse them, they see that the softness of the accusers falls on flattery! But he wants to find the pleasure of the inventor relieved from the pain of labor!',
    'Contact',
    'Application Form',
    'Ismayilli district, Kalinjak village',
    'Bakı, Meladora LLC',
    'Menus',
    'Who are we?',
    'Gardens',
    'Products',
    'Services',
    'Social responsibility',
    'Contact',
    'Useful links',
    'Frequently asked questions',
    'Career',
    'Service network',
    'FAQ',
    'Security',
    'Terms and conditions',
    'Copyright 2022 - ',
    'Powered by '
]

const changeLangToEnForValue = [
    'Search',
    'Send'
]

const changeLangToEnForPlaceholder = [
    'Search',
    'Name, Surname*',
    'Phone*',
    'E-mail*',
    'Message'
]

// Convert to Russian
const changeLangToRu = [
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Фрукты',
    'Более...',
    'Овощи',
    'Более...',
    'Зерно',
    'Более...',
    'Фрукты',
    'Более...',
    'Овощи',
    'Более...',
    'Зерно',
    'Более...',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Кто мы?',
    "На самом деле все произошло много лет назад, когда мы были в семейной поездке в Исмаиллинском районе. Красота очаровательной природы Исмаиллинского района пробудила в нас желание однажды заняться здесь сельским хозяйством. Позже, обсудив этот вопрос с нашими друзьями, мы решили основать ферму в Исмаиллы. Мы не отставали от скорости времени в своем росте. Успех, которого мы достигли за короткий промежуток времени, и тот факт, что мы продолжаем расти быстрее, свидетельствует о нашей любви к своему делу. Выращивая яблоки, груши, нектарины, сливы, вишни и грецкие орехи, мы не остановились на достигнутом, мы расширили ассортимент нашей продукции за счет посадки и производства семян.В 2022 году наша главная цель – сделать так, чтобы наш бренд появился на прилавках за пределами страны, достойный названия «сделано в АЗЕРБАЙДЖАНЕ». Мы хотим поделиться с вами следующими целями.",
    'С уважением <br> команда MELADORA',
    'Органический',
    'Удовлетворение',
    'Высокого качества',
    'Сады',
    'Зерно',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Виноград',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Капуста',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Товары',
    'Все',
    'Фрукты',
    'Овощи',
    'Зерновые',
    'Другие',
    'Яблоко',
    'Слива',
    'Груша',
    'Вишня',
    'Грецкий орех',
    'Персик',
    'Зерно',
    'Апельсин',
    'Разные оттенки',
    'Помидор',
    'Свекла',
    'Капуста',
    'Лук',
    'Огурец',
    'Морковь',
    'Услуги',
    'Системы капельного орошения',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Проектирование',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Строительство садов под ключ',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Социальная ответственность',
    'Как предприниматели, мы понимаем необходимость не только получать прибыль, но и быть полезными обществу в различных сферах, и продолжаем свою деятельность в этом направлении. Мы реализуем социально значимые программы по улучшению жизни отдельных слоев населения.<br><br>Наши друзья и окружение хорошо знают нас.<br><br>И мы гордимся тем, что являемся социально ориентированной компанией.',
    'Блоги',
    'Хранение продуктов',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Выращивание сельскохозяйственных культур',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Полив посевов',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Контакт',
    'Форма заявки',
    'Исмаиллинский район, село Калинджак',
    'Баки, ООО Меладора',
    'Меню',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Полезные ссылки',
    'Часто задаваемые вопросы',
    'Карьера',
    'Сервисная сеть',
    'ЧЗВ',
    'Безопасность',
    'Условия и положения',
    'Авторское право 2022 - ',
    'Питаться от '
]
const changeLangToRu2 = [
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Фрукты',
    'Более...',
    'Овощи',
    'Более...',
    'Зерно',
    'Более...',
    'Фрукты',
    'Более...',
    'Овощи',
    'Более...',
    'Зерно',
    'Более...',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Кто мы?',
    "На самом деле все произошло много лет назад, когда мы были в семейной поездке в Исмаиллинском районе. Красота очаровательной природы Исмаиллинского района пробудила в нас желание однажды заняться здесь сельским хозяйством. Позже, обсудив этот вопрос с нашими друзьями, мы решили основать ферму в Исмаиллы. Мы не отставали от скорости времени в своем росте. Успех, которого мы достигли за короткий промежуток времени, и тот факт, что мы продолжаем расти быстрее, свидетельствует о нашей любви к своему делу. Выращивая яблоки, груши, нектарины, сливы, вишни и грецкие орехи, мы не остановились на достигнутом, мы расширили ассортимент нашей продукции за счет посадки и производства семян.В 2022 году наша главная цель – сделать так, чтобы наш бренд появился на прилавках за пределами страны, достойный названия «сделано в АЗЕРБАЙДЖАНЕ». Мы хотим поделиться с вами следующими целями.",
    'С уважением <br> команда MELADORA',
    'Органический',
    'Удовлетворение',
    'Высокого качества',
    'Сады',
    'Зерно',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Виноград',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Капуста',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Товары',
    'Все',
    'Фрукты',
    'Овощи',
    'Зерновые',
    'Другие',
    'Яблоко',
    'Слива',
    'Груша',
    'Вишня',
    'Грецкий орех',
    'Персик',
    'Апельсин',
    'Услуги',
    'Системы капельного орошения',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Проектирование',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Строительство садов под ключ',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Социальная ответственность',
    'Как предприниматели, мы понимаем необходимость не только получать прибыль, но и быть полезными обществу в различных сферах, и продолжаем свою деятельность в этом направлении. Мы реализуем социально значимые программы по улучшению жизни отдельных слоев населения.<br><br>Наши друзья и окружение хорошо знают нас.<br><br>И мы гордимся тем, что являемся социально ориентированной компанией.',
    'Блоги',
    'Хранение продуктов',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Выращивание сельскохозяйственных культур',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Полив посевов',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Контакт',
    'Форма заявки',
    'Исмаиллинский район, село Калинджак',
    'Баки, ООО Меладора',
    'Меню',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Полезные ссылки',
    'Часто задаваемые вопросы',
    'Карьера',
    'Сервисная сеть',
    'ЧЗВ',
    'Безопасность',
    'Условия и положения',
    'Авторское право 2022 - ',
    'Питаться от '
]
const changeLangToRu3 = [
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Фрукты',
    'Более...',
    'Овощи',
    'Более...',
    'Зерно',
    'Более...',
    'Фрукты',
    'Более...',
    'Овощи',
    'Более...',
    'Зерно',
    'Более...',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Кто мы?',
    "На самом деле все произошло много лет назад, когда мы были в семейной поездке в Исмаиллинском районе. Красота очаровательной природы Исмаиллинского района пробудила в нас желание однажды заняться здесь сельским хозяйством. Позже, обсудив этот вопрос с нашими друзьями, мы решили основать ферму в Исмаиллы. Мы не отставали от скорости времени в своем росте. Успех, которого мы достигли за короткий промежуток времени, и тот факт, что мы продолжаем расти быстрее, свидетельствует о нашей любви к своему делу. Выращивая яблоки, груши, нектарины, сливы, вишни и грецкие орехи, мы не остановились на достигнутом, мы расширили ассортимент нашей продукции за счет посадки и производства семян.В 2022 году наша главная цель – сделать так, чтобы наш бренд появился на прилавках за пределами страны, достойный названия «сделано в АЗЕРБАЙДЖАНЕ». Мы хотим поделиться с вами следующими целями.",
    'С уважением <br> команда MELADORA',
    'Органический',
    'Удовлетворение',
    'Высокого качества',
    'Сады',
    'Зерно',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Виноград',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Капуста',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Товары',
    'Все',
    'Фрукты',
    'Овощи',
    'Зерновые',
    'Другие',
    'Помидор',
    'Свекла',
    'Капуста',
    'Лук',
    'Огурец',
    'Морковь',
    'Услуги',
    'Системы капельного орошения',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Проектирование',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Строительство садов под ключ',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Социальная ответственность',
    'Как предприниматели, мы понимаем необходимость не только получать прибыль, но и быть полезными обществу в различных сферах, и продолжаем свою деятельность в этом направлении. Мы реализуем социально значимые программы по улучшению жизни отдельных слоев населения.<br><br>Наши друзья и окружение хорошо знают нас.<br><br>И мы гордимся тем, что являемся социально ориентированной компанией.',
    'Блоги',
    'Хранение продуктов',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Выращивание сельскохозяйственных культур',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Полив посевов',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Контакт',
    'Форма заявки',
    'Исмаиллинский район, село Калинджак',
    'Баки, ООО Меладора',
    'Меню',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Полезные ссылки',
    'Часто задаваемые вопросы',
    'Карьера',
    'Сервисная сеть',
    'ЧЗВ',
    'Безопасность',
    'Условия и положения',
    'Авторское право 2022 - ',
    'Питаться от '
]
const changeLangToRu4 = [
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Фрукты',
    'Более...',
    'Овощи',
    'Более...',
    'Зерно',
    'Более...',
    'Фрукты',
    'Более...',
    'Овощи',
    'Более...',
    'Зерно',
    'Более...',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Кто мы?',
    "На самом деле все произошло много лет назад, когда мы были в семейной поездке в Исмаиллинском районе. Красота очаровательной природы Исмаиллинского района пробудила в нас желание однажды заняться здесь сельским хозяйством. Позже, обсудив этот вопрос с нашими друзьями, мы решили основать ферму в Исмаиллы. Мы не отставали от скорости времени в своем росте. Успех, которого мы достигли за короткий промежуток времени, и тот факт, что мы продолжаем расти быстрее, свидетельствует о нашей любви к своему делу. Выращивая яблоки, груши, нектарины, сливы, вишни и грецкие орехи, мы не остановились на достигнутом, мы расширили ассортимент нашей продукции за счет посадки и производства семян.В 2022 году наша главная цель – сделать так, чтобы наш бренд появился на прилавках за пределами страны, достойный названия «сделано в АЗЕРБАЙДЖАНЕ». Мы хотим поделиться с вами следующими целями.",
    'С уважением <br> команда MELADORA',
    'Органический',
    'Удовлетворение',
    'Высокого качества',
    'Сады',
    'Зерно',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Виноград',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Капуста',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Товары',
    'Все',
    'Фрукты',
    'Овощи',
    'Зерновые',
    'Другие',
    'Зерно',
    'Услуги',
    'Системы капельного орошения',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Проектирование',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Строительство садов под ключ',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Социальная ответственность',
    'Как предприниматели, мы понимаем необходимость не только получать прибыль, но и быть полезными обществу в различных сферах, и продолжаем свою деятельность в этом направлении. Мы реализуем социально значимые программы по улучшению жизни отдельных слоев населения.<br><br>Наши друзья и окружение хорошо знают нас.<br><br>И мы гордимся тем, что являемся социально ориентированной компанией.',
    'Блоги',
    'Хранение продуктов',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Выращивание сельскохозяйственных культур',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Полив посевов',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Контакт',
    'Форма заявки',
    'Исмаиллинский район, село Калинджак',
    'Баки, ООО Меладора',
    'Меню',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Полезные ссылки',
    'Часто задаваемые вопросы',
    'Карьера',
    'Сервисная сеть',
    'ЧЗВ',
    'Безопасность',
    'Условия и положения',
    'Авторское право 2022 - ',
    'Питаться от '
]
const changeLangToRu5 = [
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Фрукты',
    'Более...',
    'Овощи',
    'Более...',
    'Зерно',
    'Более...',
    'Фрукты',
    'Более...',
    'Овощи',
    'Более...',
    'Зерно',
    'Более...',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Кто мы?',
    "На самом деле все произошло много лет назад, когда мы были в семейной поездке в Исмаиллинском районе. Красота очаровательной природы Исмаиллинского района пробудила в нас желание однажды заняться здесь сельским хозяйством. Позже, обсудив этот вопрос с нашими друзьями, мы решили основать ферму в Исмаиллы. Мы не отставали от скорости времени в своем росте. Успех, которого мы достигли за короткий промежуток времени, и тот факт, что мы продолжаем расти быстрее, свидетельствует о нашей любви к своему делу. Выращивая яблоки, груши, нектарины, сливы, вишни и грецкие орехи, мы не остановились на достигнутом, мы расширили ассортимент нашей продукции за счет посадки и производства семян.В 2022 году наша главная цель – сделать так, чтобы наш бренд появился на прилавках за пределами страны, достойный названия «сделано в АЗЕРБАЙДЖАНЕ». Мы хотим поделиться с вами следующими целями.",
    'С уважением <br> команда MELADORA',
    'Органический',
    'Удовлетворение',
    'Высокого качества',
    'Сады',
    'Зерно',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Виноград',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Капуста',
    "Здравствуйте, это действительно боль, за которой нужно следовать. Увидим удовольствия нашего свободного человека и освободимся от легкости тела и тому подобного, которые часто им ослеплены. Стойкий!",
    'Товары',
    'Все',
    'Фрукты',
    'Овощи',
    'Зерновые',
    'Другие',
    'Разные оттенки',
    'Услуги',
    'Системы капельного орошения',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Проектирование',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Строительство садов под ключ',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Социальная ответственность',
    'Как предприниматели, мы понимаем необходимость не только получать прибыль, но и быть полезными обществу в различных сферах, и продолжаем свою деятельность в этом направлении. Мы реализуем социально значимые программы по улучшению жизни отдельных слоев населения.<br><br>Наши друзья и окружение хорошо знают нас.<br><br>И мы гордимся тем, что являемся социально ориентированной компанией.',
    'Блоги',
    'Хранение продуктов',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Выращивание сельскохозяйственных культур',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Полив посевов',
    'Компания сама по себе очень успешная. А мы их обвиняем, они видят, что мягкость обвинителей падает на лесть! Но он хочет найти удовольствие изобретателя, избавленного от боли труда!',
    'Контакт',
    'Форма заявки',
    'Исмаиллинский район, село Калинджак',
    'Баки, ООО Меладора',
    'Меню',
    'Кто мы?',
    'Сады',
    'Товары',
    'Услуги',
    'Социальная ответственность',
    'Контакт',
    'Полезные ссылки',
    'Часто задаваемые вопросы',
    'Карьера',
    'Сервисная сеть',
    'ЧЗВ',
    'Безопасность',
    'Условия и положения',
    'Авторское право 2022 - ',
    'Питаться от '
]

const changeLangToRuForValue = [
    'Поиск',
    'Отправлять'
]

const changeLangToRuForPlaceholder = [
    'Поиск',
    'Имя, Фамилия*',
    'Телефон*',
    'Э-почта*',
    'Сообщение'
]